### ISSUE TITLE
Catch multiple statements can be used in php 7.1

### ISSUE THREAD

**Issue by Flower7C3** [gigya/wordpress#133]
There is info in docks, that this plugin works in PHP version 5.6.x, 7.0.x, and 7.1.x. But catching multiple statements can be used in PHP 7.1. This problem is here
https://github.com/gigya/wordpress/blob/49109839cbd782a508b8847b8685b090a0bf1be8/GigyaAction.php#L899

**Comment by Ynhockey** [comment]
Hi Flower7C3, we noticed this issue as well, thanks for bringing it up. It has been resolved in branch php_5_compatibility. It will be merged in the upcoming version.

**Comment by Ynhockey** [comment]
Update has been released with v5.10. Hope this helps.
