### ISSUE TITLE
Uncaught Error: Class 'Gigya\PHP\GSRequest' not found in

### ISSUE THREAD

**Issue by gfrera** [gigya/wordpress#160]
Dear Sirs,
following the installations steps we have verified a blocking error 

Uncaught Error: Class 'Gigya\PHP\GSRequest' not found in .../wp-content/plugins/wordpress-master/cms_kit/GigyaApiRequest.php

":11 Stack trace: #0 /home/ticketing/public_html/wp-content/plugins/wordpress-master/GigyaAction.php(133): require_once() #1 /home/ticketing/public_html/wp-includes/class-wp-hook.php(287): Gigya\WordPress\GigyaAction->init('') #2 /home/ticketing/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 /home/ticketing/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /home/ticketing/public_html/wp-settings.php(546): do_action('init') #5 /home/ticketing/public_html/wp-config.php(105): require_once('/home/ticketing...') #6 /home/ticketing/public_html/wp-load.php(37): require_once('/home/ticketing...') #7 /home/ticketing/public_html/wp-login.php(12): require('/home/ticketing...') #8 {main} thrown... "

Any idea to solve the issue?

Reagrds,

Giovanni

**Comment by Ynhockey** [comment]
Hi gfrera,

The 6.x+ versions require composer install, because the plugin now uses Gigya PHP SDK as a 3rd party library. The newest version also allows you to install the plugin itself with Composer, but you should run composer install with any 6.x version.

Hope that helps!
