### ISSUE TITLE
Remove the delete_user action

### ISSUE THREAD

**Issue by kyfr59** [gigya/wordpress#169]
Hi, I don't find the way to remove the "delete_user" action from the plugin. 

The code below doesn't works.

```
function remove_delete_user_actions() {
    remove_action( 'delete_user', array( '\Gigya\WordPress\GigyaAction', 'deleteUser') );
}
add_action( 'init', 'remove_delete_user_actions' );
```
I've tried to handle the remove_action() priorities, to instanciate the GigyaAction class before pass it to remove_action() but nothing works.

Any idea ?

Thanks.

**Comment by Ynhockey** [comment]
Hi kyfr59,

Can you elaborate on why you want to remove this action? Do you want to keep users deleted on the WordPress side, so that they are still available on the Gigya side? Can you give a use case example?

Thanks.

**Comment by kyfr59** [comment]
Thanks for your reply.

It's a customer request : he don't want to remove Gigya users when they're deleted from the Wordpress admin.

Franck.

**Comment by Ynhockey** [comment]
Hi,

I have opened a new branch with this change:
https://github.com/gigya/wordpress/compare/develop...gigya_action_variable

You should be able to remove actions now, with remove_action(), for instance:

`remove_action( 'delete_user', array( $gigyaAction, 'deleteUser' ) );`

Can't promise anything about official release dates, but if you merge this branch with yours, it should be update-proof from my side.

**Comment by kyfr59** [comment]
Thank you very much for your responsiveness Yan !

**Comment by kyfr59** [comment]
Hi Yan,

It works fine :

```
global $gigyaAction;
remove_action( 'delete_user', [ $gigyaAction, 'deleteUser' ] );
```

Franck.
