### ISSUE TITLE
Login Stopped Working Since End of 2023

### ISSUE THREAD

**Issue by nicolacalvio** [gigya/wordpress#191]
Hello,

I am experiencing an issue with the Gigya plugin for WordPress. Since the end of 2023, the login functionality has stopped working unexpectedly from one day to the next. Below are the details:

Steps to Reproduce:

Attempt to log in using a screenset
Observe the failure to log in.
Expected Behavior:
Users should be able to log in successfully

Observed Behavior:
Users are unable to log in. The login process fails without providing specific error messages.

Technical Details:

WordPress Version: 6.4.2
Gigya Plugin Version: [latest version as of issue date]
Other Plugins Installed:
+------------------------------------------+--------+------------------------------+------------+
| name                                     | status | update                       | version    |
+------------------------------------------+--------+------------------------------+------------+
| 2fas-light                               | active | none                         | 3.3.1      |
| a3-lazy-load                             | active | available                    | 2.7.1      |
| aryo-activity-log                        | active | available                    | 2.9.0      |
| acfml                                    | active | none                         | 2.0.5      |
| advanced-custom-fields-pro               | active | available                    | 6.2.5      |
| advanced-post-queries                    | active | available                    | 1.1.1      |
| all-in-one-wp-security-and-firewall      | active | available                    | 5.2.5      |
| ari-stream-quiz                          | active | version higher than expected | 1.8.4      |
| batch-translate-independently            | active | none                         | 1.0        |
| custom-post-type-ui                      | active | available                    | 1.15.1     |
| dokan-lite                               | active | available                    | 3.9.6      |
| dokan-pro                                | active | available                    | 3.9.8      |
| dynamic-content-for-elementor            | active | available                    | 2.12.7     |
| easy-wp-smtp                             | active | available                    | 2.2.0      |
| ele-custom-skin                          | active | available                    | 3.1.7      |
| ele-custom-skin-pro                      | active | none                         | 3.2.4      |
| elementor                                | active | available                    | 3.18.3     |
| elementor-pro                            | active | available                    | 3.18.3     |
| essential-addons-for-elementor-lite      | active | available                    | 4.8.3      |
| jet-menu                                 | active | none                         | 2.4.0      |
| jet-search                               | active | none                         | 3.2.1      |
| jet-smart-filters                        | active | none                         | 3.3.1      |
| jetwidgets-for-elementor                 | active | available                    | 1.0.15     |
| jetwoo-widgets-for-elementor             | active | none                         | 1.1.6      |
| wp-maintenance-mode                      | active | available                    | 2.6.9      |
| meta-tag-manager                         | active | available                    | 3.0.2      |
| qty-increment-buttons-for-woocommerce    | active | none                         | 2.7.5      |
| gigya                                    | active | none                         | 6.5.0      |
| spotlight-social-photo-feeds             | active | available                    | 1.6.8      |
| spotlight-social-photo-feeds-premium     | active | available                    | 1.6.8      |
| ultimate-elementor                       | active | available                    | 1.36.28    |
| unlimited-elements-for-elementor-premium | active | available                    | 1.4.83     |
| updraftplus                              | active | available                    | 2.23.14.26 |
| woo-variation-swatches                   | active | available                    | 2.0.30     |
| woo-products-widgets-for-elementor       | active | none                         | 2.0.0      |
| woocommerce                              | active | available                    | 8.5.1      |
| woocommerce-multilingual                 | active | available                    | 5.3.2      |
| woo-shortcodes-kit                       | active | none                         | 2.0.2      |
| wp-sweep                                 | active | none                         | 1.1.8      |
| insert-headers-and-footers               | active | available                    | 2.1.7      |
| wp-downgrade                             | active | none                         | 1.2.6      |
| wp-google-maps                           | active | available                    | 9.0.32     |
| wp-google-maps-pro                       | active | none                         | 8.1.22     |
| wpml-media-translation                   | active | none                         | 2.7.3      |
| sitepress-multilingual-cms               | active | none                         | 4.6.9      |
| wp-seo-multilingual                      | active | none                         | 2.1.0      |
| wpml-sticky-links                        | active | none                         | 1.5.4      |
| wpml-string-translation                  | active | none                         | 3.2.9      |
| wp-user-avatar                           | active | available                    | 2.2.16     |
| custom-redirections-for-wshk             | active | available                    | 1.2.1      |
| wordpress-seo                            | active | available                    | 21.8.1     |
| wordpress-seo-premium                    | active | none                         | 21.8       |
+------------------------------------------+--------+------------------------------+------------+

Theme: Hello elementor
Debugging Efforts:

Verified that tokens and other SAP-related aspects are working correctly.
Confirmed that the issue seems to be on the WordPress side of the integration.
Ensured that I am using the latest version of both WordPress and the Gigya plugin.
Additional Information:

![Screenshot 2024-05-30 170820](https://github.com/gigya/wordpress/assets/29726308/a0e22e0c-5dda-4c39-ae1c-99325e761500)
![Screenshot 2024-05-30 170824](https://github.com/gigya/wordpress/assets/29726308/4e45e677-73a0-442e-886f-4c04a7485461)

Request:
Please investigate this issue and provide guidance on how to resolve it. If any additional information is needed, I am happy to provide it.

Thank you for your attention to this matter.

Best regards,
Nicola Calvio

**Comment by shaharzillber** [comment]
Hey,
 it has been fixed.
